#!/bin/bash

# Global setup
sudo apt install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
sudo apt install python3-venv
pip install wheel

# Project setup
python3 -m venv venv/
source venv/bin/activate
pip install -r requirements.txt
deactivate

echo -e '\nSuccess!'
